#!/usr/bin/env bash
# ========================
#  snapshot-packages.sh
#  Re-captures the installed package set into packages/.
#  Run this after installing or removing things, so the repo keeps
#  describing the machine you actually have.
# ========================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

PACKAGES_DIR="$ROOT_DIR/packages"
mkdir -p "$PACKAGES_DIR"

info "Reading installed packages..."

pacman_explicit="$(pacman -Qqe | sort)"
aur_explicit="$(pacman -Qqm | sort)"

{
    echo "# Repository packages installed on this machine."
    echo "# Generated by scripts/snapshot-packages.sh on $(date -I)"
    echo "# Replay with: ./scripts/install-packages.sh"
    echo "$pacman_explicit"
} > "$PACKAGES_DIR/pacman-explicit.list"

{
    echo "# AUR / foreign packages installed on this machine."
    echo "# Generated by scripts/snapshot-packages.sh on $(date -I)"
    echo "$aur_explicit"
} > "$PACKAGES_DIR/aur-explicit.list"

count_repo=$(grep -cvE '^\s*(#|$)' "$PACKAGES_DIR/pacman-explicit.list")
count_aur=$(grep -cvE '^\s*(#|$)' "$PACKAGES_DIR/aur-explicit.list")

success "Snapshot written"
info "  packages/pacman-explicit.list  $count_repo packages"
info "  packages/aur-explicit.list      $count_aur packages"

if [ -d "$ROOT_DIR/.git" ] && have git; then
    echo ""
    # Committing needs a deliberate answer. Unlike the other prompts, the
    # non-interactive default is no: a cron job or CI run that invokes this
    # script should never push a commit on its own.
    if [ ! -t 0 ] || confirm "Commit the updated snapshot?" n; then
        if [ ! -t 0 ]; then
            info "Not a terminal, skipping the commit. Re-run interactively to commit."
        else
            git -C "$ROOT_DIR" add packages/
            git -C "$ROOT_DIR" commit -m "chore(packages): snapshot machine ($(date +%Y-%m-%d))"
            success "Committed"
        fi
    fi
fi
