#!/usr/bin/env bash
# ========================
#  sync.sh
#  Keeps the repository describing the machine, then reports what it did.
#
#  Two directions of drift matter, and only one of them is automatic:
#
#    captured but stale  a managed path exists in $HOME but the repo has
#                        no copy, or an old one. This is captured, because
#                        adding a file cannot destroy work in the repo.
#
#    overlapping         the path exists in both and the contents differ.
#                        Reported, never resolved. Deciding which side
#                        wins is a judgement call, and silently taking
#                        one is how a refactor gets reverted by a timer
#                        at 3am.
#
#  Nothing is ever pushed. The repository is public, so pushing is the one
#  irreversible step and it stays a human decision.
#
#  Usage: ./scripts/sync.sh [--dry-run] [--no-commit] [--quiet]
# ========================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

ALLOWLIST="$ROOT_DIR/config/managed-paths.list"
REPORT_FILE="${XDG_STATE_HOME:-$HOME/.local/state}/automatizations/sync-report.txt"

DRY_RUN=0
DO_COMMIT=1
QUIET=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run|-n) DRY_RUN=1; shift ;;
        --no-commit)  DO_COMMIT=0; shift ;;
        --quiet|-q)   QUIET=1; shift ;;
        -h|--help)    grep '^#' "$0" | sed 's/^# \?//'; exit 0 ;;
        *) error "Unknown option: $1" ;;
    esac
done

[ -f "$ALLOWLIST" ] || error "Missing allowlist: $ALLOWLIST"
[ -d "$ROOT_DIR/.git" ] || error "Not a git repository: $ROOT_DIR"

# Split the allowlist into captured paths and report-only paths.
# sed rather than grep for the "?" prefix: in basic regex \? means
# "optional", so '^\?' matches an empty string and warns about escaping.
mapfile -t SYNCED < <(grep -vE '^\s*(#|$)' "$ALLOWLIST" | sed -n '/^?/!p')
mapfile -t REPORT_ONLY < <(sed -n 's/^?//p' "$ALLOWLIST")

captured=0
captured_paths=()
problems=()
pkg_added=()
pkg_removed=()

note() { [ "$QUIET" -eq 1 ] || printf '%s\n' "$*"; }

# Where the repo keeps its copy of a $HOME path.
repo_path() {
    local rel="$1"
    if [ -e "$ROOT_DIR/ktemplated/$rel" ]; then
        printf '%s\n' "$ROOT_DIR/ktemplated/$rel"
    else
        printf '%s\n' "$ROOT_DIR/dotfiles/$rel"
    fi
}

# ========================
#  Packages
# ========================
sync_packages() {
    local list="$ROOT_DIR/packages/pacman-explicit.list"
    local aurlist="$ROOT_DIR/packages/aur-explicit.list"
    [ -f "$list" ] || { note "  ${YELLOW}no packages/pacman-explicit.list, skipping${RESET}"; return; }

    local installed listed pkg
    installed="$(mktemp)"; listed="$(mktemp)"
    trap 'rm -f "$installed" "$listed"' RETURN

    pacman -Qqe 2>/dev/null | sort -u > "$installed"
    grep -vE '^\s*(#|$)' "$list" | sort -u > "$listed"

    # Installed but not listed: a fresh machine would not get these.
    while IFS= read -r pkg; do
        [ -z "$pkg" ] && continue
        pkg_added+=("$pkg")
    done < <(comm -23 "$installed" "$listed")

    # Listed but not installed: the list is describing a machine that
    # no longer exists.
    while IFS= read -r pkg; do
        [ -z "$pkg" ] && continue
        pkg_removed+=("$pkg")
    done < <(comm -13 "$installed" "$listed")

    if [ "${#pkg_removed[@]}" -gt 0 ] && [ "$DO_COMMIT" -eq 1 ] && [ "$DRY_RUN" -eq 0 ]; then
        note "  ${YELLOW}${#pkg_removed[@]} listed package(s) are no longer installed:${RESET}"
        note "        ${pkg_removed[*]}"
        note "        ${CYAN}Run scripts/snapshot-packages.sh to drop them from the list.${RESET}"
    fi

    # Only rewrite the list when something new appeared. Removing entries is
    # a decision, not a side effect.
    if [ "${#pkg_added[@]}" -gt 0 ] && [ "$DRY_RUN" -eq 0 ]; then
        {
            echo "# Repository packages installed on this machine."
            echo "# Generated by scripts/snapshot-packages.sh on $(date -I)"
            echo "# Replay with: ./scripts/install-packages.sh"
            cat "$installed"
        } > "$list"
        note "  ${GREEN}captured${RESET} ${#pkg_added[@]} new package(s) in packages/"
    fi

    if [ -f "$aurlist" ] && [ "$DO_COMMIT" -eq 1 ]; then
        local ainstalled alisted
        ainstalled="$(pacman -Qqm 2>/dev/null | sort -u)"
        alisted="$(grep -vE '^\s*(#|$)' "$aurlist" | sort -u)"
        if [ "$ainstalled" != "$alisted" ] && [ -n "$ainstalled" ]; then
            [ "$DRY_RUN" -eq 1 ] || {
                echo "# AUR / foreign packages installed on this machine." > "$aurlist"
                echo "# Generated by scripts/snapshot-packages.sh on $(date -I)" >> "$aurlist"
                printf '%s\n' "$ainstalled" >> "$aurlist"
            }
            note "  ${GREEN}captured${RESET} AUR package changes"
        fi
    fi
}

# ========================
#  Config paths
# ========================
# True when git would ignore this repo-relative path. Reusing the same
# .gitignore for both git and the sync keeps one policy in charge of what
# is a config file and what is runtime noise.
repo_ignores() {
    local rel="$1"
    git -C "$ROOT_DIR" check-ignore -q -- "$rel" 2>/dev/null
}

# Compare an allowlisted directory file by file.
#   $1 home dir, $2 repo dir, $3 path as written in the allowlist
compare_dirs() {
    local home="$1" repo="$2" rel="$3"
    local f rsub hsub

    # Files the repo manages that no longer match the machine.
    while IFS= read -r f; do
        rsub="${f#"$repo"/}"
        repo_ignores "${f#"$ROOT_DIR"/}" && continue
        hsub="$home/$rsub"
        if [ ! -e "$hsub" ]; then
            problems+=("in the repo but not on this machine: $rel/$rsub")
        elif ! diff -q "$f" "$hsub" >/dev/null 2>&1; then
            problems+=("changed outside the repo, review it: $rel/$rsub")
        fi
    done < <(find "$repo" -type f)

    # Files the app wrote that the repo has never seen.
    # The ignore check has to run on the repo-relative path, because that is
    # the path space .gitignore is written in. Checking the $HOME-relative
    # path would silently miss every rule, and would happily offer to
    # capture conf.d/secrets.fish.
    local repo_rel
    repo_rel="${repo#"$ROOT_DIR"/}"
    while IFS= read -r f; do
        rsub="${f#"$home"/}"
        hsub="$repo/$rsub"
        [ -e "$hsub" ] && continue
        repo_ignores "$repo_rel/$rsub" && continue
        case "$rsub" in
            # Extensionless files in a config dir are usually state, and a
            # wrong guess here is what the allowlist exists to prevent.
            *.*) ;;
            *) continue ;;
        esac
        note "  ${CYAN}new${RESET}      $rel/$rsub"
        if [ "$DRY_RUN" -eq 0 ]; then
            mkdir -p "$(dirname "$hsub")"
            cp -a "$f" "$hsub"
            captured=$((captured + 1))
            captured_paths+=("$hsub")
        fi
    done < <(find "$home" -type f)
}

sync_paths() {
    local rel repo
    local templated

    for rel in "${SYNCED[@]}"; do
        [ -z "$rel" ] && continue
        repo="$(repo_path "$rel")"
        local home="$HOME/$rel"

        # A templated path is machine specific by definition. Its repo copy
        # holds @HOME@ and @GIT_NAME@ placeholders, so diffing it against
        # the real file would report a difference on every single run.
        case "$repo" in
            "$ROOT_DIR/ktemplated/"*) templated=1 ;;
            *) templated=0 ;;
        esac

        if [ ! -e "$home" ]; then
            problems+=("listed in the allowlist but not on this machine: $rel")
            continue
        fi

        if [ ! -e "$repo" ]; then
            # The additive case. Capturing a path the repo does not have
            # cannot destroy anything that was already committed.
            if [ -L "$home" ]; then
                problems+=("allowlisted path is a symlink to nowhere: $rel -> $(readlink "$home")")
                continue
            fi
            note "  ${GREEN}new${RESET}      $rel"
            if [ "$DRY_RUN" -eq 0 ]; then
                mkdir -p "$(dirname "$repo")"
                cp -a "$home" "$repo"
                captured=$((captured + 1))
                captured_paths+=("$repo")
            fi
            continue
        fi

        [ "$templated" -eq 1 ] && continue

        # Once installed, home is a symlink into the repo and both sides are
        # the same bytes. Nothing to compare and nothing to capture.
        if [ -L "$home" ]; then
            local target
            target="$(readlink -f "$home")"
            if [[ "$target" == "$ROOT_DIR/dotfiles/"* || "$target" == "$ROOT_DIR/ktemplated/"* ]]; then
                continue
            fi
            problems+=("allowlisted path links outside the repo: $rel -> $target")
            continue
        fi

        if [ -d "$home" ] && [ -d "$repo" ]; then
            compare_dirs "$home" "$repo" "$rel"
        elif ! diff -q "$repo" "$home" >/dev/null 2>&1; then
            problems+=("changed outside the repo, review it: $rel")
        fi
    done

    for rel in "${REPORT_ONLY[@]}"; do
        [ -z "$rel" ] && continue
        if [ ! -e "$HOME/$rel" ] && [ ! -e "$(repo_path "$rel")" ]; then
            problems+=("generated file missing, run install-machine.sh: $rel")
        fi
    done
}

# ========================
#  Main
# ========================
mkdir -p "$(dirname "$REPORT_FILE")"

{
    echo "sync report: $(date -I)"
    echo "repo: $ROOT_DIR"
    echo
} > "$REPORT_FILE"

note "${BOLD}Config${RESET}"
sync_paths

note ""
note "${BOLD}Packages${RESET}"
sync_packages

# ========================
#  Commit
# ========================
committed=0
if [ "$DO_COMMIT" -eq 1 ] && [ "$DRY_RUN" -eq 0 ] && [ "$captured" -gt 0 ]; then
    note ""
    note "${BOLD}Commit${RESET}"
    # Stage only what the allowlist covers, then scan before committing.
    while IFS= read -r rel; do
        [ -z "$rel" ] && continue
        repo="$(repo_path "$rel")"
        [ -e "$repo" ] && git -C "$ROOT_DIR" add -- "$repo"
    done < <(printf '%s\n' "${SYNCED[@]}")
    git -C "$ROOT_DIR" add -- packages/

    if git -C "$ROOT_DIR" diff --cached --quiet; then
        note "  nothing to commit"
    else
        # The backstop. If this fails, nothing is written to the history.
        if ! "$SCRIPT_DIR/secret-scan.sh" --staged; then
            # Roll the staging back and delete what was just captured. Leaving
            # the file in the worktree would only move the problem: it would
            # sit there untracked until some later "git add -A" committed it
            # without passing through the scan.
            git -C "$ROOT_DIR" reset -q
            for p in "${captured_paths[@]}"; do
                rm -rf "$p"
            done
            # Packages were rewritten from the machine, not from home, so
            # they stay staged and are safe to keep.
            git -C "$ROOT_DIR" add -- packages/
            note "  ${RED}secret scan failed${RESET}"
            note "  rolled back the staging and deleted ${#captured_paths[@]} captured file(s)"
            problems+=("secret scan blocked a commit; the captured files were removed")
        else
            if git -C "$ROOT_DIR" commit -q -m "chore(sync): capture machine state ($(date +%Y-%m-%d))"; then
                committed=1
                note "  ${GREEN}committed${RESET} (not pushed)"
            fi
        fi
    fi
fi

# ========================
#  Report
# ========================
if [ "${#problems[@]}" -gt 0 ]; then
    {
        echo "needs attention:"
        printf '  - %s\n' "${problems[@]}"
    } | tee -a "$REPORT_FILE" >&2
fi

{
    echo "captured files: $captured"
    echo "packages added: ${#pkg_added[@]}"
    echo "packages listed but absent: ${#pkg_removed[@]}"
    echo "committed: $committed"
} | tee -a "$REPORT_FILE" >/dev/null

if [ "${#problems[@]}" -eq 0 ] && [ "$captured" -eq 0 ] && [ "${#pkg_added[@]}" -eq 0 ]; then
    note ""
    success "Everything in sync"
fi

[ -s "$REPORT_FILE" ] && [ "$QUIET" -eq 0 ] && note "  report: $REPORT_FILE"
exit 0
