[colors.primary]
background = '#181826'
foreground = '#f2f2f3'

[colors.cursor]
text = '#181826'
cursor = '#f2f2f3'

[colors.vi_mode_cursor]
text = '#181826'
cursor = '#6767e4'

[colors.search.matches]
foreground = '#1f1f32'
background = '#cc66cc'

[colors.search.focused_match]
foreground = '#1f1f32'
background = '#6767e4'

[colors.footer_bar]
foreground = '#1f1f32'
background = '#e3e3e8'

[colors.hints.start]
foreground = '#1f1f32'
background = '#945cd6'

[colors.hints.end]
foreground = '#1f1f32'
background = '#945cd6'

[colors.selection]
text = '#afafb6'
background = '#1f1f32'


[colors.normal]
black   = '#1f1f32'
red     = '#fd4663'
green   = '#7173f1'
yellow  = '#9d66e0'
blue    = '#cc66cc'
magenta = '#9393ec'
cyan    = '#bc96e9'
white   = '#f2f2f3'


[colors.bright]
black   = '#636473'
red     = '#fd4663'
green   = '#7173f1'
yellow  = '#9d66e0'
blue    = '#cc66cc'
magenta = '#9393ec'
cyan    = '#bc96e9'
white   = '#f2f2f3'


[colors.dim]
black   = '#1f1f32'
red     = '#fd4663'
green   = '#7173f1'
yellow  = '#9d66e0'
blue    = '#cc66cc'
magenta = '#9393ec'
cyan    = '#bc96e9'
white   = '#f2f2f3'
